# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EKxjOS6yc57XeEbJDync5F3iMRKbhqqO
"""

import numpy as np
import matplotlib.pyplot as plt

x = np.linspace(0, 10, 100)
y = np.sin(x)

plt.figure(figsize=(8, 6))
plt.plot(x, y, label="Sinus(x)", color="blue")
plt.title("Sinus Funksiyasining Grafiki")
plt.xlabel("X qiymatlari")
plt.ylabel("Y qiymatlari")
plt.legend()
plt.grid(True)
plt.show()

x_random = np.random.uniform(0, 10, 50)
y_random = np.random.uniform(0, 10, 50)

plt.figure(figsize=(8, 6))
plt.scatter(x_random, y_random, color="blue", label="Nuqtalar")
plt.title("Tasodifiy Nuqtalar Scatter Grafiki")
plt.xlabel("X qiymatlari")
plt.ylabel("Y qiymatlari")
plt.legend()
plt.grid(True)
plt.show()